;
; MSX1-BIOS HOOKS
; Version 0.1
;

HKEYI:          equ 0FD9AH              ; Manipulador de Interrupção (0x0C4A)
HTIMI:          equ 0FD9FH              ; Manipulador de Interrupção (0x0C53)
HCHPU:          equ 0FDA4H              ; Rotina CHPUT (0x08C0)
HDSPC:          equ 0FDA9H              ; Mostra cursor (0x09E6)
HERAC:          equ 0FDAEH              ; Apaga cursor (0x0A33)
HDSPF:          equ 0FDB3H              ; Rotina DSPFNK (0x0B2B)
HERAF:          equ 0FDB8H              ; Rotina ERAFNK (0x0B15)
HTOTE:          equ 0FDBDH              ; Rotina TOTEXT (0x0842)
HCHGE:          equ 0FDC2H              ; Rotina CHGET (0x10CE)
HINIP:          equ 0FDC7H              ; Cópia da tabela de caracteres (ROM->VDP) (0x071E)
HKEYC:          equ 0FDCCH              ; Decodificador do teclado (0x1025)
HKYEA:          equ 0FDD1H              ; Decodificador do teclado (0x0F10)
HNMI:           equ 0FDD6H              ; Rotina NMI (0x1398)
HPINL:          equ 0FDDBH              ; Rotina PINLIN (0x23BF)
HQINL:          equ 0FDE0H              ; Rotina QINLIN (0x23CC)
HINLI:          equ 0FDE5H              ; Rotina INLIN (0x23D5)
HONGO:          equ 0FDEAH              ; ON <dispositivo> GOSUB (0x7810)
HDSKO:          equ 0FDEFH              ; DSKO0x (0x7C16)
HSETS:          equ 0FDF4H              ; SET (0x7C1B)
HNAME:          equ 0FDF9H              ; NAME (0x7C20)
HKILL:          equ 0FDFEH              ; KILL (0x7C25)
HIPL:           equ 0FE03H              ; IPL (0x7C2A)
HCOPY:          equ 0FE08H              ; COPY (0x7C2F)
HCMD:           equ 0FE0DH              ; DSKF (0x7C39)
HDSKI:          equ 0FE17H              ; DSKI0x (0x7C3E)
HATTR:          equ 0FE1CH              ; ATTR0x (0x7C43)
HLSET:          equ 0FE21H              ; LSET (0x7C48)
HRSET:          equ 0FE26H              ; RSET (0x7C4D)
HFIEL:          equ 0FE2BH              ; FIELD (0x7C52)
HMKI:           equ 0FE30H              ; MKI0x (0x7C57)
HMKS:           equ 0FE35H              ; MKS0x (0x7C5C)
HMKD:           equ 0FE3AH              ; MKD0x (0x7C61)
HCVI:           equ 0FE3FH              ; CVI (0x7C66)
HCVS:           equ 0FE44H              ; CVS (0x7C6B)
HCVD:           equ 0FE49H              ; CVS (0x7C70)
HGETP:          equ 0FE4EH              ; Localizar FCB (0x6A93)
HSETF:          equ 0FE53H              ; Localizar FCB (0x6AB3)
HNOFO:          equ 0FE58H              ; OPEN: not found (0x6AF6)
HNULO:          equ 0FE5DH              ; OPEN (0x6B0F)
HNTFL:          equ 0FE62H              ; Fecha buffer 0 de I/O (0x6B3B)
HMERG:          equ 0FE67H              ; MERGE/LOAD (0x6B63)
HSAVE:          equ 0FE6CH              ; SAVE (0x6BA6)
HBINS:          equ 0FE71H              ; SAVE (0x6BCE)
HBINL:          equ 0FE76H              ; MERGE/LOAD (0x6BD4)
HFILE:          equ 0FE7BH              ; FILES (0x6C2F)
HDGET:          equ 0FE80H              ; GET/PUT (0x6C3B)
HFILO:          equ 0FE85H              ; Saída Sequencial (0x6C51)
HINDS:          equ 0FE8AH              ; Entrada Sequencial (0x6C79)
HRSLF:          equ 0FE8FH              ; INPUT0x (0x6CD8)
HSAVD:          equ 0FE94H              ; LOC (0x6D03), LOF (0x6D14), EOF (0x6D25), FPOS (0x6D39)
HLOC:           equ 0FE99H              ; LOC (0x6D0F)
HLOF:           equ 0FE9EH              ; LOF (0x6D20)
HEOF:           equ 0FEA3H              ; EOF (0x6D33)
HFPOS:          equ 0FEA8H              ; FPOS (0x6D43)
HBAKU:          equ 0FEADH              ; LINE INPUT# (0x6E36)
HPARD:          equ 0FEB2H              ; Análise de nome de dispositivo (0x6F15)
HNODE:          equ 0FEB7H              ; Análise de nome de dispositivo (0x6F33)
HPOSD:          equ 0FEBCH              ; Análise de nome de dispositivo (0x6F37)
HDEVN:          equ 0FEC1H              ; Não utilizado
HGEND:          equ 0FEC6H              ; Despachador de função de I/O (0x6F8F)
HRUNC:          equ 0FECBH              ; Processar-Liberar (0x629A)
HCLEA:          equ 0FED0H              ; Processar-Liberar (0x62A1)
HLOPD:          equ 0FED5H              ; Processar-Liberar (0x62AF)
HSTKE:          equ 0FEDAH              ; Limpar Pilha (0x62F0)
HISFL:          equ 0FEDFH              ; Rotina ISFLIO (0x145F)
HOUTD:          equ 0FEE4H              ; Rotina OUTDO (0x1B46)
HCRDO:          equ 0FEE9H              ; CR, LF para OUTDO (0x7328)
HDSKC:          equ 0FEEEH              ; Entrada de linha no laço principal (0x7274)
HDOGR:          equ 0FEF3H              ; Traçar linha (0x593C)
HPRGE:          equ 0FEF8H              ; Fim de programa (0x4039)
HERRP:          equ 0FEFDH              ; Manipulador de erro (0x40DC)
HERRF:          equ 0FF02H              ; Manipulador de erro (0x40FD)
HREAD:          equ 0FF07H              ; "OK" do laço principal (0x4128)
HMAIN:          equ 0FF0CH              ; Laço Principal (0x4134)
HDIRD:          equ 0FF11H              ; Comando direto do laço principal (0x41A8)
HFINI:          equ 0FF16H              ; Fim do laço principal (0x4237)
HFINE:          equ 0FF1BH              ; Fim do laço principal (0x4247)
HCRUN:          equ 0FF20H              ; Tokenização (0x42B9)
HCRUS:          equ 0FF25H              ; Tokenização (0x4353)
HISRE:          equ 0FF2AH              ; Tokenização (0x437C)
HNTFN:          equ 0FF2FH              ; Tokenização (0x43A4)
HNOTR:          equ 0FF34H              ; Tokenização (0x44EB)
HSNGF:          equ 0FF39H              ; FOR (0x45D1)
HNEWS:          equ 0FF3EH              ; laço de execução: novo comando (0x4601)
HGONE:          equ 0FF43H              ; laço de execução (0x4646)
HCHRG:          equ 0FF48H              ; Rotina CHRGTR (0x4666)
HRETU:          equ 0FF4DH              ; RETURN (0x4821)
HPRTF:          equ 0FF52H              ; PRINT (0x4A5E)
HCOMP:          equ 0FF57H              ; PRINT (0x4A94)
HFINP:          equ 0FF5CH              ; PRINT (0x4AFF)
HTRMN:          equ 0FF61H              ; Erro READ/INPUT (0x484D)
HFRME:          equ 0FF66H              ; Avaliador de expressões (0x4C6D)
HNTPL:          equ 0FF6BH              ; Avaliador de expressões (0x4CA6)
HEVAL:          equ 0FF70H              ; Avaliador de fatores (0x4DD9)
HOKNO:          equ 0FF75H              ; Avaliador de fatores (0x4F2C)
HFING:          equ 0FF7AH              ; Avaliador de fatores (0x4F3E)
HISMI:          equ 0FF7FH              ; laço de execução (0x51C3)
HWIDT:          equ 0FF84H              ; WIDTH (0x51CC)
HLIST:          equ 0FF89H              ; LIST (0x522E)
HBUFL:          equ 0FF8EH              ; Destokenização (0x532D)
HFRQI:          equ 0FF93H              ; Conversão para inteiro (0x543F)
HSCNE:          equ 0FF98H              ; Conversão de número de linha para ponteiro (0x5514)
HFRET:          equ 0FF9DH              ; Liberar descritor (0x67EE)
HPTRG:          equ 0FFA2H              ; Busca de variável (0x5EA9)
HPHYD:          equ 0FFA7H              ; Rotina PHYDIO (0x148A)
HFORM:          equ 0FFACH              ; Rotina FORMAT (0x148E)
HERRO:          equ 0FFB1H              ; Manipulador de erro (0x406F)
HLPTO:          equ 0FFB6H              ; Rotina LPTOUT (0x085D)
HLPTS:          equ 0FFBBH              ; Rotina LPTSTT (0x0884)
HSCRE:          equ 0FFC0H              ; SCREEN (0x79CC)
HPLAY:          equ 0FFC5H              ; PLAY (0x73E5)
